cure_heart: &cure_heart
  girl_name:    cure_heart
  human_name:   相田マナ
  precure_name: キュアハート
  cast_name:    生天目仁美
  created_date: 2013-02-03 # episode 1
  color:        pink
  birthday:     8/4
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    みなぎる愛！ キュアハート！
    響け愛の鼓動！ドキドキプリキュア！
    愛を無くした悲しいジコチューさん、
    このキュアハートがあなたのドキドキ取り戻してみせる！
  extra_names:
  - キュアハート・パルテノンモード
  attack_messages:
    - |-
      あなたに届け！マイスイートハート！
  transform_calls:
    - love_link
cure_diamond: &cure_diamond
  girl_name:    cure_diamond
  human_name:   菱川六花
  precure_name: キュアダイヤモンド
  cast_name:    寿美菜子
  created_date: 2013-02-17 # episode 3
  color:        blue
  birthday:     9/17
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    英知の光！ キュアダイヤモンド！
    響け愛の鼓動！ドキドキプリキュア！
    人の思いを踏みにじるなんて許せない、
    このキュアダイヤモンドがあなたの頭を冷やしてあげる！
  extra_names:
  attack_messages:
    - |-
      きらめきなさい！トゥインクルダイヤモンド！
  transform_calls:
    - love_link
cure_rosetta: &cure_rosetta
  girl_name:    cure_rosetta
  human_name:   四葉ありす
  precure_name: キュアロゼッタ
  cast_name:    渕上舞
  created_date: 2013-02-24 # episode 4
  color:        yellow
  birthday:     5/28
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    ひだまりポカポカ キュアロゼッタ！
    響け愛の鼓動！ドキドキプリキュア！
    世界を制するのは愛だけです、
    さぁ、あなたも私と愛を育んでくださいな
  extra_names:
  attack_messages:
    - |-
      カッチカチの！ロゼッタウォール！
  transform_calls:
    - love_link
cure_sword: &cure_sword
  girl_name:    cure_sword
  human_name:   剣崎真琴
  precure_name: キュアソード
  cast_name:    宮本佳那子
  created_date: 2013-02-03 # episode 1
  color:        purple
  birthday:     11/4
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    勇気の刃！ キュアソード！
    響け愛の鼓動！ドキドキプリキュア！
    このキュアソードが愛の剣で
    あなたの野望を断ち切ってみせる！
  extra_names:
  attack_messages:
    - |-
      ひらめけ！ホーリーソード！
  transform_calls:
    - love_link
cure_ace: &cure_ace
  girl_name:    cure_ace
  human_name:   円亜久里
  precure_name: キュアエース
  cast_name:    釘宮理恵
  created_date: 2013-06-30 # episode 22
  color:        red
  transform_message: |-
    プリキュアドレスアップ！
    (キュピラッパー！)
    愛の切り札！ キュアエース！
    響け愛の鼓動！ドキドキプリキュア！
    美しさは正義の証し、ウインク一つで、
    あなたのハートを射抜いて差し上げますわ
  extra_names:
  attack_messages:
    - |-
      ときめきなさい！エースショット！
      ばきゅ〜ん！！
  transform_calls:
    - dress_up
heart:
  <<: *cure_heart
diamond:
  <<: *cure_diamond
rosetta:
  <<: *cure_rosetta
sword:
  <<: *cure_sword
ace:
  <<: *cure_ace
