cure_lovely: &cure_lovely
  girl_name:    cure_lovely
  human_name:   愛乃めぐみ
  precure_name: キュアラブリー
  cast_name:    中島愛
  created_date: 2014-02-02 # episode 1
  color:        pink
  transform_message: |-
    (かわルンルン！)
    プリキュアくるりんミラーチェンジ！
    世界に広がるビッグな愛！キュアラブリー！
    ハピネス注入！幸せチャージ！
    ハピネスチャージプリキュア！
  extra_names:
  - キュアラブリー チェリーフラメンコ
  - キュアラブリー ロリポップヒップポップ
  - フォーエバーラブリー
  attack_messages:
    - |-
      愛の光を聖なる力に！
      ラブプリブレス！
      プリキュア！ピンキーラブシュート！！
      愛よ、天に帰れ！
      (ゴクラ〜ク…)
    - |-
      (かわルンルン！)
      プリキュアくるりんミラーチェンジ！チェリーフラメンコ！
      プリキュア！パッションダイナマイト！！
      オーレ！
    - |-
      (かわルンルン！)
      プリキュアくるりんミラーチェンジ！ロリポップヒップポップ！！！
      プリキュア！ポップンソニックアタック！！
    - |-
      プリキュア！フォーエバーハピネスシャワー！！
  transform_calls:
    - kururin_mirror_change
cure_princess: &cure_princess
  girl_name:       cure_princess
  human_name:      白雪ひめ
  human_full_name: ヒメルダ・ウインドウ・キュアクイーン・オブ・ザ・ブルースカイ
  precure_name:    キュアプリンセス
  cast_name:       潘めぐみ
  created_date:    2014-02-02 # episode 1
  color:           blue
  transform_message: |-
    (かわルンルン！)
    プリキュアくるりんミラーチェンジ！
    天空に舞う蒼き風！キュアプリンセス！
    ハピネス注入！幸せチャージ！
    ハピネスチャージプリキュア！
  extra_names:
  - キュアプリンセス シャーベットバレエ
  - キュアプリンセス マカダミアフラダンス
  attack_messages:
    - |-
      勇気の光を聖なる力へ！
      ラブプリブレス！
      プリキュア！ブルーハッピーシュート！！
      勇気よ、天に帰れ！
      (ゴクラ〜ク…)
    - |-
      (かわルンルン！)
      プリキュアくるりんミラーチェンジ！シャーベットバレエ！！
      プリキュア！アラベスクシャワー！！
    - |-
      (かわルンルン！)
      プリキュアくるりんミラーチェンジ！マカダミアフラダンス！！
      プリキュア！ハワイアンアロハロエ！！
  transform_calls:
    - kururin_mirror_change
cure_honey: &cure_honey
  girl_name:    cure_honey
  human_name:   大森ゆうこ
  precure_name: キュアハニー
  cast_name:    北川里奈
  created_date: 2014-03-15 # NS3
  color:        yellow
  transform_message: |-
    (かわルンルン！)
    プリキュアくるりんミラーチェンジ！
    大地に実る命の光！キュアハニー！
    ハピネス注入！幸せチャージ！
    ハピネスチャージプリキュア！
  extra_names:
  - キュアハニー ポップコーンチア
  attack_messages:
    - |-
      命の光を聖なる力へ！
      ハニーバトン！
      プリキュア！スパークリングバトンアタック！！
      イエイ！
      命よ、天に帰れ！
      (ゴクラ〜ク…)
    - |-
      (かわルンルン！)
      プリキュアくるりんミラーチェンジ！ポップコーンチア！！
      プリキュア！リボンハートエクスプロージョン！！
      ビクトリー！！
    - |-
      (かわルンルン！)
      プリキュアくるりんミラーチェンジ！ココナッツサンバ！！
      プリキュア！マラカスリズムスパーク！！
      マンボ！！
  transform_calls:
    - kururin_mirror_change
cure_fortune: &cure_fortune
  girl_name:    cure_fortune
  human_name:   氷川いおな
  precure_name: キュアフォーチュン
  cast_name:    戸松遥
  created_date: 2014-06-29
  color:        purple
  transform_message: |-
    (かわルンルン！)
    プリキュアきらりんスターシンフォニー！
    夜空にきらめく希望の星！キュアフォーチュン！
    ハピネス注入！幸せチャージ！
    ハピネスチャージプリキュア！
  extra_names:
  - キュアフォーチュン パインアラビアン
  - キュアフォーチュン あんみつこまち
  attack_messages:
    - |-
      星の光を聖なる力に！
      フォーチュンタンバリン！
      プリキュア！スターライトアセンション！！
      星よ、天に帰れ！
      (ゴクラ〜ク…)
    - |-
      (かわルンルン！)
      プリキュアきらりんスターシンフォニー！パインアラビアン！
      プリキュア！オリエンタルドリーム！
    - |-
      (かわルンルン！)
      プリキュアきらりんスターシンフォニー！あんみつこまち！
      プリキュア！桜吹雪の舞！
  transform_calls:
    - kirarin_star_symphony
lovely:
  <<: *cure_lovely
princess:
  <<: *cure_princess
honey:
  <<: *cure_honey
fortune:
  <<: *cure_fortune
