cure_wonderful: &cure_wonderful
  girl_name:    cure_wonderful
  human_name:   犬飼こむぎ
  precure_name: キュアワンダフル
  cast_name:    長縄まりあ
  color:        pink
  created_date: 2024-02-04 # episode 1
  birthday:     5/13
  transform_message: |-
    ワンダフルパクト！
    プリキュア！マイエボリューション！
    スリー！
    ツー！
    ワン！
    みんな大好き素敵な世界！
    キュアワンダフル！
    いっしょに遊ぼ♪
    せーの！
    わんだふるぷりきゅあ！
  # extra_names:
  attack_messages:
    - |-
      フレンドリータクト！
      ワンダフルをきみに！
      ワン！ワン！わ〜ん！
      ガルガルな心、飛んでけー！！
      プリキュア！フレンドリベラーレ！
  transform_calls:
    - my_evolution
wonderful:
  <<: *cure_wonderful

cure_friendy: &cure_friendy
  girl_name:    cure_friendy
  human_name:   犬飼いろは
  precure_name: キュアフレンディ
  cast_name:    種崎敦美
  color:        purple
  created_date: 2024-02-11 # episode 2
  birthday:     8/7
  transform_message: |-
    ワンダフルパクト！
    プリキュア！マイエボリューション！
    スリー！
    ツー！
    ワン！
    みんなの笑顔で彩る世界！
    キュアフレンディ！
    あなたの声をきかせて
    せーの！
    わんだふるぷりきゅあ！
  # extra_names:
  attack_messages:
    - |-
      フレンドリータクト！
      ワンダフルをきみに！
      ワン！ワン！わ〜ん！
      ガルガルな心、飛んでけー！！
      プリキュア！フレンドリベラーレ！
  transform_calls:
    - my_evolution
friendy:
  <<: *cure_friendy

cure_nyammy: &cure_nyammy
  girl_name:    cure_nyammy
  human_name:   猫屋敷ユキ
  precure_name: キュアニャミー
  cast_name:    松田颯水
  color:        blue
  created_date: 2024-05-26 # episode 17
  birthday:     12/21
  transform_message: |-
    シャイニーキャッツパクト！
    プリキュア！マイエボリューション！
    ほっぺにきらめき！
    リップはキュートに！
    気高くかわいくきらめく世界！
    キュアニャミー！
    仕方ない、構ってあげる
    ニャンダフルプリキュア！
  # extra_names:
  attack_messages:
    - |-
      アミティーリボンタンバリン！
      ニャンダフルをあなたに！
      ニャン！ドゥ！トロワ！
      ガルガルの心さようなら！
      プリキュア！アミティールミエール！
  transform_calls:
    - my_evolution
nyammy:
  <<: *cure_nyammy

cure_lillian: &cure_lillian
  girl_name:    cure_lillian
  human_name:   猫屋敷まゆ
  precure_name: キュアリリアン
  cast_name:    上田麗奈
  color:        green
  created_date: 2024-06-09 # episode 19
  birthday:     11/5
  transform_message: |-
    シャイニーキャッツパクト！
    プリキュア！マイエボリューション！
    目元にきらめき！
    リップはキュートに！
    結んで紡いでつながる世界！
    キュアリリアン！
    こわくない、こわくない
    ニャンダフルプリキュア！
  # extra_names:
  attack_messages:
    - |-
      アミティーリボンタンバリン！
      ニャンダフルをあなたに！
      ニャン！ドゥ！トロワ！
      ガルガルの心さようなら！
      プリキュア！アミティールミエール！
  transform_calls:
    - my_evolution
lillian:
  <<: *cure_lillian
