cure_answer: &cure_answer
  girl_name:    cure_answer
  human_name:   明智あんな
  precure_name: キュアアンサー
  cast_name:    千賀光莉
  color:        purple
  created_date: 2026-02-01 # episode 1
  birthday:     1/24
  transform_message: |-
    オープン！ジュエルキュアウォッチ！
    どんな謎でもはなまる解決！
    名探偵 キュアアンサー！
  # extra_names:
  attack_messages:
    - |-
  transform_calls:
    - open_jewel_cure_watch
answer:
  <<: *cure_answer

cure_mystique: &cure_mystique
  girl_name:    cure_mystique
  human_name:   小林みくる
  precure_name: キュアミスティック
  cast_name:    本渡楓
  color:        pink
  # created_date: 2026-xx-xx # episode x
  birthday:     4/22
  transform_message: |-
    オープン！ジュエルキュアウォッチ！
    重ねた推理で笑顔にジャンプ！
    名探偵 キュアミスティック！
  # extra_names:
  attack_messages:
    - |-
  transform_calls:
    - open_jewel_cure_watch
mystique:
  <<: *cure_mystique

cure_eclair: &cure_eclair
  girl_name:    cure_eclair
  # human_name:
  # precure_name: キュアエクレール
  cast_name:
  color:        green
  # created_date: 2026-xx-xx # episode x
  # birthday:     xx/xx
  transform_message: |-
    解き放て！内なる真実の香り
    名探偵 キュアエクレール！
  # extra_names:
  attack_messages:
    - |-
  transform_calls:
    # -
eclair:
  <<: *cure_eclair

cure_arcana_shadow: &cure_arcana_shadow
  girl_name:    cure_arcana_shadow
  human_name:   森亜るるか
  precure_name: キュアアルカナ・シャドウ！
  cast_name:    東山奈央
  color:        black
  # created_date: 2026-xx-xx # episode x
  birthday:     11/1
  transform_message: |-
    神秘と秘密で包み込む
    キュアアルカナ・シャドウ！
  # extra_names:
  attack_messages:
    - |-
  transform_calls:
    # -
arcana_shadow:
  <<: *cure_arcana_shadow
