# unmarked
cure_black: &cure_black
  human_name:   美墨なぎさ
  precure_name: キュアブラック
  created_date: 2004-02-01 # episode 1
  transform_message: |-
    デュアル・オーロラ・ウェイブ！！
    光の使者、キュアブラック！
    ふたりはプリキュア！
    闇の力のしもべ達よ！
    とっととお家に帰りなさい！
  extra_names:
cure_white: &cure_white
  human_name:   雪城ほのか
  precure_name: キュアホワイト
  created_date: 2004-02-01 # episode 1
  transform_message: |-
    デュアル・オーロラ・ウェイブ！！
    光の使者、キュアホワイト！
    ふたりはプリキュア！
    闇の力のしもべ達よ！
    とっととお家に帰りなさい！
  extra_names:
black:
  <<: *cure_black
white:
  <<: *cure_white

# max_heart
shiny_luminous: &shiny_luminous
  human_name:   九条ひかり
  precure_name: シャイニールミナス
  created_date: 2005-03-06 # episode 5
  transform_message: |-
    ルミナス・シャイニングストリーム！
    輝く命、シャイニールミナス！
    光の心と光の意志、すべてを一つにするために！
  extra_names:
luminous:
  <<: *shiny_luminous

# splash_star
cure_bloom: &cure_bloom
  human_name:   日向咲
  precure_name: キュアブルーム
  created_date: 2006-02-05 # episode 1
  transform_message: |-
    デュアル・スピリチュアル・パワー！
    花開け大地に！
    輝く金の花！ キュアブルーム！
    ふたりはプリキュア！
    聖なる泉を汚す者よ！
    阿漕な真似はお止めなさい！
cure_egret: &cure_egret
  human_name:   美翔舞
  precure_name: キュアイーグレット
  created_date: 2006-02-05 # episode 1
  transform_message: |-
    デュアル・スピリチュアル・パワー！
    羽ばたけ空に！
    煌めく銀の翼！ キュアイーグレット！
    ふたりはプリキュア！
    聖なる泉を汚す者よ！
    阿漕な真似はお止めなさい！
cure_bright: &cure_bright
  human_name:   日向咲
  precure_name: キュアブライト
  created_date: 2006-09-03 # episode 30
  transform_message: |-
    デュアル・スピリチュアル・パワー！
    未来を照らし！
    天空に満ちる月！ キュアブライト！
    ふたりはプリキュア！
    聖なる泉を汚す者よ！
    阿漕な真似はお止めなさい！
cure_windy: &cure_windy
  human_name:   美翔舞
  precure_name: キュアウィンディ
  created_date: 2006-09-03 # episode 30
  transform_message: |-
    デュアル・スピリチュアル・パワー！
    勇気を運べ！
    大地に薫る月！ キュアウィンディ！
    ふたりはプリキュア！
    聖なる泉を汚す者よ！
    阿漕な真似はお止めなさい！
bloom:
  <<: *cure_bloom
egret:
  <<: *cure_egret
bright:
  <<: *cure_bright
windy:
  <<: *cure_windy

# yes
cure_dream:  &cure_dream
  human_name:   夢原のぞみ
  precure_name: キュアドリーム
  created_date: 2007-02-04 # episode 1
  transform_message: |-
    プリキュア！メタモルフォーゼ！
    大いなる希望の力、キュアドリーム！
    希望の力と未来の光！
    華麗に羽ばたく5つの心！
    Yes！プリキュア5！
  extra_names:
cure_rouge:  &cure_rouge
  human_name:   夏木りん
  precure_name: キュアルージュ
  created_date: 2007-02-11 # episode 2
  transform_message: |-
    プリキュア！メタモルフォーゼ！
    情熱の赤い炎、キュアルージュ！
    希望の力と未来の光！
    華麗に羽ばたく5つの心！
    Yes！プリキュア5！
  extra_names:
cure_lemonade:  &cure_lemonade
  human_name:   春日野うらら
  precure_name: キュアレモネード
  created_date: 2007-02-18 # episode 3
  transform_message: |-
    プリキュア！メタモルフォーゼ！
    はじけるレモンの香り、キュアレモネード！
    希望の力と未来の光！
    華麗に羽ばたく5つの心！
    Yes！プリキュア5！
  extra_names:
cure_mint:  &cure_mint
  human_name:   秋元こまち
  precure_name: キュアミント
  created_date: 2007-02-25 # episode 4
  transform_message: |-
    プリキュア！メタモルフォーゼ！
    安らぎの緑の大地、キュアミント！
    希望の力と未来の光！
    華麗に羽ばたく5つの心！
    Yes！プリキュア5！
  extra_names:
cure_aqua:  &cure_aqua
  human_name:   水無月かれん
  precure_name: キュアアクア
  created_date: 2007-03-11 # episode 6
  transform_message: |-
    プリキュア！メタモルフォーゼ！
    知性の青き泉、キュアアクア！
    希望の力と未来の光！
    華麗に羽ばたく5つの心！
    Yes！プリキュア5！
  extra_names:
dream:
  <<: *cure_dream
rouge:
  <<: *cure_rouge
lemonade:
  <<: *cure_lemonade
mint:
  <<: *cure_mint
aqua:
  <<: *cure_aqua

# yes_gogo
milky_rose: &milky_rose
  human_name:   美々野くるみ
  precure_name: ミルキィローズ
  created_date: 2008-04-06 # episode 10
  transform_message: |-
    スカイローズ・トランスレイト！
    青いバラは秘密のしるし！ ミルキィローズ！
  extra_names:
rose:
  <<: *milky_rose

# fresh
cure_peach: &cure_peach
  human_name:   桃園ラブ
  precure_name: キュアピーチ
  created_date: 2009-02-01 # episode 1
  transform_message: |-
    チェインジ！プリキュア・ビートアップ！
    ピンクのハートは愛あるしるし！
    もぎたてフレッシュ、キュアピーチ！
    レッツプリキュア！
  extra_names:
  - キュアエンジェルピーチ
cure_berry: &cure_berry
  human_name:   蒼乃美希
  precure_name: キュアベリー
  created_date: 2009-02-08 # episode 2
  transform_message: |-
    チェインジ！プリキュア・ビートアップ！
    ブルーのハートは希望のしるし！
    つみたてフレッシュ、キュアベリー！
    レッツプリキュア！
  extra_names:
  - キュアエンジェルベリー
cure_pine: &cure_pine
  human_name:   山吹祈里
  precure_name: キュアパイン
  created_date: 2009-02-15 # episode 3
  transform_message: |-
    チェインジ！プリキュア・ビートアップ！
    イエローハートは祈りのしるし！
    とれたてフレッシュ、キュアパイン！
    レッツプリキュア！
  extra_names:
  - キュアエンジェルパイン
cure_passion: &cure_passion
  human_name:   東せつな
  precure_name: キュアパッション
  created_date: 2009-07-12 # episode 23
  transform_message: |-
    チェインジ！プリキュア・ビートアップ！
    真っ赤なハートは幸せの証！
    熟れたてフレッシュ、キュアパッション！
    レッツプリキュア！
  extra_names:
  - キュアエンジェルパッション
peach:
  <<: *cure_peach
berry:
  <<: *cure_berry
pine:
  <<: *cure_pine
passion:
  <<: *cure_passion

# heart_catch
cure_blossom: &cure_blossom
  human_name:   花咲つぼみ
  precure_name: キュアブロッサム
  created_date: 2010-02-07 # episode 1
  transform_message: |-
    (プリキュアの種、いくですぅ！)
    プリキュア！オープンマイハート！
    大地に咲く一輪の花！ キュアブロッサム！
    ハートキャッチ、プリキュア！
  extra_names:
  - スーパーキュアブロッサム
cure_marine: &cure_marine
  human_name:   来海えりか
  precure_name: キュアマリン
  created_date: 2010-02-21 # episode 3
  transform_message: |-
    (プリキュアの種、いくですぅ！)
    プリキュア！オープンマイハート！
    海風に揺れる一輪の花！ キュアマリン！
    ハートキャッチ、プリキュア！
  extra_names:
  - スーパーキュアマリン
cure_sunshine: &cure_sunshine
  human_name:   明堂院いつき
  precure_name: キュアサンシャイン
  created_date: 2010-07-18 # episode 23
  transform_message: |-
    (プリキュアの種、いくですぅ！)
    プリキュア！オープンマイハート！
    陽の光浴びる一輪の花！ キュアサンシャイン！
    ハートキャッチ、プリキュア！
  extra_names:
  - スーパーキュアサンシャイン
cure_moonlight: &cure_moonlight
  human_name:   月影ゆり
  precure_name: キュアムーンライト
  created_date: 2010-09-26 # episode 33
  transform_message: |-
    (プリキュアの種、いくですぅ！)
    プリキュア！オープンマイハート！
    月光に冴える一輪の花 キュアムーンライト！
    ハートキャッチ、プリキュア！
  extra_names:
  - スーパーキュアムーンライト
blossom:
  <<: *cure_blossom
marine:
  <<: *cure_marine
sunshine:
  <<: *cure_sunshine
moonlight:
  <<: *cure_moonlight

# suite
cure_melody: &cure_melody
  human_name:   北条響
  precure_name: キュアメロディ
  created_date: 2011-02-06 # episode 1
  transform_message: |-
    レッツプレイ！プリキュアモジュレーション！！
    爪弾くは荒ぶる調べ！ キュアメロディ！
    響け4人の組曲！スイートプリキュア！
  extra_names:
  - クレッシェンドメロディ
cure_rhythm: &cure_rhythm
  human_name:   南野奏
  precure_name: キュアリズム
  created_date: 2011-02-06 # episode 1
  transform_message: |-
    レッツプレイ！プリキュアモジュレーション！！
    爪弾くはたおやかな調べ！ キュアリズム！
    響け4人の組曲！スイートプリキュア！
  extra_names:
  - クレッシェンドリズム
cure_beat: &cure_beat
  human_name:   黒川エレン
  precure_name: キュアビート
  created_date: 2011-07-10 # episode 21
  transform_message: |-
    レッツプレイ！プリキュアモジュレーション！！
    爪弾くは魂の調べ！ キュアビート！
    響け4人の組曲！スイートプリキュア！
  extra_names:
  - クレッシェンドビート
cure_muse: &cure_muse
  human_name:   調辺アコ
  precure_name: キュアミューズ
  created_date: 2011-10-16 # episode 35
  transform_message: |-
    レッツプレイ！プリキュアモジュレーション！！
    爪弾くは女神の調べ！ キュアミューズ！
    響け4人の組曲！スイートプリキュア！
  extra_names:
  - クレッシェンドミューズ
melody:
  <<: *cure_melody
rhythm:
  <<: *cure_rhythm
beat:
  <<: *cure_beat
muse:
  <<: *cure_muse

# smile
cure_happy: &cure_happy
  human_name:   星空みゆき
  precure_name: キュアハッピー
  created_date: 2012-02-05 # episode 1
  transform_message: |-
    (レディ？)
    プリキュア・スマイルチャージ！
    (ゴー！ゴー！レッツ・ゴー！ハッピー！！)
    キラキラ輝く未来の光！ キュアハッピー！
    5つの光が導く未来！
    輝け！スマイルプリキュア！
  extra_names:
  - プリンセスハッピー
  - ウルトラハッピー
cure_sunny: &cure_sunny
  human_name:   日野あかね
  precure_name: キュアサニー
  created_date: 2012-02-12 # episode 2
  transform_message: |-
    (レディ？)
    プリキュア・スマイルチャージ！
    (ゴー！ゴー！レッツ・ゴー！サニー！！)
    太陽サンサン熱血パワー！ キュアサニー！
    5つの光が導く未来！
    輝け！スマイルプリキュア！
  extra_names:
  - プリンセスサニー
  - ウルトラサニー
cure_peace: &cure_peace
  human_name:   黄瀬やよい
  precure_name: キュアピース
  created_date: 2012-02-19 # episode 3
  transform_message: |-
    (レディ？)
    プリキュア・スマイルチャージ！
    (ゴー！ゴー！レッツ・ゴー！ピース！！)
    ピカピカピカリンジャンケンポン！ キュアピース！
    5つの光が導く未来！
    輝け！スマイルプリキュア！
  extra_names:
  - プリンセスピース
  - ウルトラピース
cure_march: &cure_march
  human_name:   緑川なお
  precure_name: キュアマーチ
  created_date: 2012-02-26 # episode 4
  transform_message: |-
    (レディ？)
    プリキュア・スマイルチャージ！
    (ゴー！ゴー！レッツ・ゴー！マーチ！！)
    勇気リンリン直球勝負！ キュアマーチ！
    5つの光が導く未来！
    輝け！スマイルプリキュア！
  extra_names:
  - プリンセスマーチ
  - ウルトラマーチ
cure_beauty: &cure_beauty
  human_name:   青木れいか
  precure_name: キュアビューティ
  created_date: 2012-03-04 # episode 5
  transform_message: |-
    (レディ？)
    プリキュア・スマイルチャージ！
    (ゴー！ゴー！レッツ・ゴー！ビューティ！！)
    しんしんと降り積もる清き心！ キュアビューティ！
    5つの光が導く未来！
    輝け！スマイルプリキュア！
  extra_names:
  - プリンセスビューティ
  - ウルトラビューティ
happy:
  <<: *cure_happy
sunny:
  <<: *cure_sunny
peace:
  <<: *cure_peace
march:
  <<: *cure_march
beauty:
  <<: *cure_beauty

# dokidoki
cure_heart: &cure_heart
  human_name:   相田マナ
  precure_name: キュアハート
  created_date: 2013-02-03 # episode 1
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    みなぎる愛！ キュアハート！
    響け愛の鼓動！ドキドキプリキュア！
    愛を無くした悲しいジコチューさん、
    このキュアハートがあなたのドキドキ取り戻してみせる！
  extra_names:
  - キュアハート・エンゲージモード
cure_diamond: &cure_diamond
  human_name:   菱川六花
  precure_name: キュアダイヤモンド
  created_date: 2013-02-17 # episode 3
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    英知の光！ キュアダイヤモンド！
    響け愛の鼓動！ドキドキプリキュア！
    人の思いを踏みにじるなんて許せない、
    このキュアダイヤモンドがあなたの頭を冷やしてあげる！
  extra_names:
cure_rosetta: &cure_rosetta
  human_name:   四葉ありす
  precure_name: キュアロゼッタ
  created_date: 2013-02-24 # episode 4
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    ひだまりポカポカ キュアロゼッタ！
    響け愛の鼓動！ドキドキプリキュア！
    世界を制するのは愛だけです、
    さぁ、あなたも私と愛を育んでくださいな
  extra_names:
cure_sword: &cure_sword
  human_name:   剣崎真琴
  precure_name: キュアソード
  created_date: 2013-02-03 # episode 1
  transform_message: |-
    プリキュアラブリンク！
    L! O! V! E!
    勇気の刃！ キュアソード！
    響け愛の鼓動！ドキドキプリキュア！
    このキュアソードが愛の剣で
    あなたの野望を断ち切ってみせる！
  extra_names:
cure_ace: &cure_ace
  human_name:   円亜久里
  precure_name: キュアエース
  created_date: 2013-06-30 # episode 22
  transform_message: |-
    プリキュアドレスアップ！
    (キュピラッパー！)
    愛の切り札！ キュアエース！
    響け愛の鼓動！ドキドキプリキュア！
    美しさは正義の証し、ウインク一つで、
    あなたのハートを射抜いて差し上げますわ
  extra_names:
heart:
  <<: *cure_heart
diamond:
  <<: *cure_diamond
rosetta:
  <<: *cure_rosetta
sword:
  <<: *cure_sword
ace:
  <<: *cure_ace

# happiness_charge
cure_lovely: &cure_lovely
  human_name:   愛乃めぐみ
  precure_name: キュアラブリー
  created_date: 2014-02-02 # episode 1
  transform_message: |-
    かわルンルン！
    プリキュアくるりんミラーチェンジ！
    世界に広がるビッグな愛！キュアラブリー！
    ハピネス注入！幸せチャージ！
  extra_names:
cure_princess: &cure_princess
  human_name:   白雪ひめ
  precure_name: キュアプリンセス
  created_date: 2014-02-02 # episode 1
  transform_message: |-
    かわルンルン！
    プリキュアくるりんミラーチェンジ！
    天空に舞う蒼き風！キュアプリンセス！
    ハピネス注入！幸せチャージ！
  extra_names:
cure_honey: &cure_honey
  human_name:   TODO_cure_honey
  precure_name: キュアハニー
  created_date: # TODO episode
  transform_message: |-
    TODO
  extra_names:
#cure_fortune: &cure_fortune
#  human_name:   TODO_cure_fortune
#  precure_name: キュアフォーチュン
#  created_date: # TODO episode
#  transform_message: |-
#    TODO
#  extra_names:

lovely:
  <<: *cure_lovely
princess:
  <<: *cure_princess
honey:
  <<: *cure_honey
#fortune:
#  <<: *cure_fortune
