#######################################################
unmarked: &unmarked
  series_name: unmarked
  title: ふたりはプリキュア
  started_date: 2004-02-01
  ended_date:   2005-01-30
  girls:
  - cure_black
  - cure_white
futari_wa_pretty_cure:
  <<: *unmarked
#######################################################
max_heart: &max_heart
  series_name: max_heart
  title: ふたりはプリキュア Max Heart
  started_date: 2005-02-06
  ended_date:   2006-01-29
  girls:
  - cure_black
  - cure_white
  - shiny_luminous
futari_wa_pretty_cure_max_heart:
  <<: *max_heart
#######################################################
splash_star: &splash_star
  series_name: splash_star
  title: ふたりはプリキュア Splash☆Star
  started_date: 2006-02-05
  ended_date:   2007-01-28
  girls:
  - cure_bloom
  - cure_egret
futari_wa_pretty_cure_splash_star:
  <<: *splash_star
#######################################################
"yes": &yes
  series_name: "yes"
  title: Yes！ プリキュア5
  started_date: 2007-02-04
  ended_date:   2008-01-27
  girls:
  - cure_dream
  - cure_rouge
  - cure_lemonade
  - cure_mint
  - cure_aqua
yes_precure_five:
  <<: *yes
yes_precure5:
  <<: *yes
#######################################################
yes_gogo: &yes_gogo
  series_name: yes_gogo
  title: Yes！ プリキュア5 Go Go！
  started_date: 2008-02-03
  ended_date:   2009-01-25
  girls:
  - cure_dream
  - cure_rouge
  - cure_lemonade
  - cure_mint
  - cure_aqua
  - milky_rose
yes_precure_five_gogo:
  <<: *yes_gogo
yes_precure5_gogo:
  <<: *yes_gogo
#######################################################
fresh: &fresh
  series_name: fresh
  title: フレッシュプリキュア！
  started_date: 2009-02-01
  ended_date:   2010-01-31
  girls:
  - cure_peach
  - cure_berry
  - cure_pine
  - cure_passion
fresh_precure:
  <<: *fresh
#######################################################
heart_catch: &heart_catch
  series_name: heart_catch
  title: ハートキャッチプリキュア！
  started_date: 2010-02-07
  ended_date:   2011-01-30
  girls:
  - cure_blossom
  - cure_marine
  - cure_sunshine
  - cure_moonlight
heart_catch_precure:
  <<: *heart_catch
#######################################################
suite: &suite
  series_name: suite
  title: スイートプリキュア♪
  started_date: 2011-02-06
  ended_date:   2012-01-29
  girls:
  - cure_melody
  - cure_rhythm
  - cure_beat
  - cure_muse
suite_precure:
  <<: *suite
#######################################################
smile: &smile
  series_name: smile
  title: スマイルプリキュア！
  started_date: 2012-02-05
  ended_date:   2013-01-27
  girls:
  - cure_happy
  - cure_sunny
  - cure_peace
  - cure_march
  - cure_beauty
smile_precure:
  <<: *smile
#######################################################
dokidoki: &dokidoki
  series_name: dokidoki
  title: ドキドキ！プリキュア
  started_date: 2013-02-03
  ended_date:   2014-01-26
  girls:
  - cure_heart
  - cure_diamond
  - cure_rosetta
  - cure_sword
  - cure_ace
dokidoki_precure:
  <<: *dokidoki
#######################################################
happiness_charge: &happiness_charge
  series_name: happiness_charge
  title: ハピネスチャージプリキュア！
  started_date: 2014-02-02
  ended_date:   2015-01-25
  girls:
  - cure_lovely
  - cure_princess
  - cure_honey
  - cure_fortune
happiness_charge_precure:
  <<: *happiness_charge
#######################################################
go_princess: &go_princess
  series_name: go_princess
  title: Go!プリンセスプリキュア
  started_date: 2015-02-01
  ended_date:   2016-01-31
  girls:
  - cure_flora
  - cure_mermaid
  - cure_twinkle
  - cure_scarlet
go_princess_precure:
  <<: *go_princess
#######################################################
maho_girls: &maho_girls
  series_name: maho_girls
  title: 魔法つかいプリキュア！
  started_date: 2016-02-07
  ended_date:   2017-01-29
  girls:
  - cure_miracle
  - cure_magical
  - cure_felice
maho_girls_precure:
  <<: *maho_girls
#######################################################
a_la_mode: &a_la_mode
  series_name: a_la_mode
  title: キラキラ☆プリキュアアラモード
  started_date: 2017-02-05
  ended_date:   2018-01-28
  girls:
  - cure_whip
  - cure_custard
  - cure_gelato
  - cure_macaron
  - cure_chocolat
  - cure_parfait
alamode:
  <<: *a_la_mode
kirakira_precure_a_la_mode:
  <<: *a_la_mode
kirakira_precure_alamode:
  <<: *a_la_mode
#######################################################
hugtto: &hugtto
  series_name: hugtto
  title: ＨＵＧっと！プリキュア
  started_date: 2018-02-04
  ended_date:   2019-01-27
  girls:
  - cure_yell
  - cure_ange
  - cure_etoile
  - cure_macherie
  - cure_amour
hugtto_precure:
  <<: *hugtto
#######################################################
star_twinkle: &star_twinkle
  series_name: star_twinkle
  title: スター☆トゥインクルプリキュア
  started_date: 2019-02-03
  ended_date:   2020-01-26
  girls:
    - cure_star
    - cure_milky
    - cure_soleil
    - cure_selene
    - cure_cosmo
star_twinkle_precure:
  <<: *star_twinkle
#######################################################
healingood: &healingood
  series_name: healingood
  title: ヒーリングっど♥プリキュア
  started_date: 2020-02-02
  # ended_date:   2021-01-
  girls:
    - cure_grace
    - cure_fontaine
    - cure_sparkle
healingood_precure:
  <<: *healingood
