#######################################################
unmarked: &unmarked
  title: ふたりはプリキュア
  started_date: 2004-02-01
  ended_date:   2005-01-30
  girls:
  - cure_black
  - cure_white
futari_wa_pretty_cure:
  <<: *unmarked
#######################################################
max_heart: &max_heart
  title: ふたりはプリキュア Max Heart
  started_date: 2005-02-06
  ended_date:   2006-01-29
  girls:
  - cure_black
  - cure_white
  - shiny_luminous
futari_wa_pretty_cure_max_heart:
  <<: *max_heart
#######################################################
splash_star: &splash_star
  title: ふたりはプリキュア Splash Star
  started_date: 2006-02-05
  ended_date:   2007-01-28
  girls:
  - cure_bloom
  - cure_egret
futari_wa_pretty_cure_splash_star:
  <<: *splash_star
#######################################################
"yes": &yes
  title: Yes！ プリキュア5
  started_date: 2007-02-04
  ended_date:   2008-01-27
  girls:
  - cure_dream
  - cure_rouge
  - cure_lemonade
  - cure_mint
  - cure_aqua
yes_precure_five:
  <<: *yes
yes_precure5:
  <<: *yes
#######################################################
yes_gogo: &yes_gogo
  title: Yes！ プリキュア5 Go Go！
  started_date: 2008-02-03
  ended_date:   2009-01-25
  girls:
  - cure_dream
  - cure_rouge
  - cure_lemonade
  - cure_mint
  - cure_aqua
  - milky_rose
yes_precure_five_gogo:
  <<: *yes_gogo
yes_precure5_gogo:
  <<: *yes_gogo
#######################################################
fresh: &fresh
  title: フレッシュプリキュア！
  started_date: 2009-02-01
  ended_date:   2010-01-31
  girls:
  - cure_peach
  - cure_berry
  - cure_pine
  - cure_passion
fresh_precure:
  <<: *fresh
#######################################################
heart_catch: &heart_catch
  title: ハートキャッチプリキュア！
  started_date: 2010-02-07
  ended_date:   2011-01-30
  girls:
  - cure_blossom
  - cure_marine
  - cure_sunshine
  - cure_moonlight
heart_catch_precure:
  <<: *heart_catch
#######################################################
suite: &suite
  title: スイートプリキュア♪
  started_date: 2011-02-06
  ended_date:   2012-01-29
  girls:
  - cure_melody
  - cure_rhythm
  - cure_beat
  - cure_muse
suite_precure:
  <<: *suite
#######################################################
smile: &smile
  title: スマイルプリキュア！
  started_date: 2012-02-05
  ended_date:   2013-01-27
  girls:
  - cure_happy
  - cure_sunny
  - cure_peace
  - cure_march
  - cure_beauty
smile_precure:
  <<: *smile
#######################################################
dokidoki: &dokidoki
  title: ドキドキ！プリキュア
  started_date: 2013-02-03
  ended_date:   2014-01-26
  girls:
  - cure_heart
  - cure_diamond
  - cure_rosetta
  - cure_sword
  - cure_ace
dokidoki_precure:
  <<: *dokidoki
#######################################################
happiness_charge: &happiness_charge
  title: ハピネスチャージプリキュア！
  started_date: 2014-02-02
  ended_date:   2015-01-25
  girls:
  - cure_lovely
  - cure_princess
  - cure_honey
  - cure_fortune
happiness_charge_precure:
  <<: *happiness_charge
#######################################################
go_princess: &go_princess
  title: Go!プリンセスプリキュア
  started_date: 2015-02-01
  # ended_date:   2016-01-
  girls:
  - cure_flora
  - cure_mermaid
  - cure_twinkle
go_princess_precure:
  <<: *go_princess
